In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
read=pd.read_csv('FINAL_DATASET.csv')

In [ ]:
read.shape

(66913, 9)

In [ ]:
read['SRI'].replace('', np.nan, inplace=True)

In [ ]:
read.dropna(subset=['SRI'], inplace=True)

In [ ]:
read.shape

(66600, 9)

In [ ]:
read.drop(read.index[read['SRI'] == '#NAME?'], inplace = True)

In [ ]:
read.shape

(66490, 9)

In [ ]:
target = read['Degree_of_congestion']
df1 = read.copy()
df1 = df1.drop('Degree_of_congestion', axis =1)
df1.shape

(66490, 8)

In [ ]:
le = LabelEncoder()
target = le.fit_transform(target)
target

array([3, 2, 0, ..., 0, 3, 2])

In [ ]:
target2 = df1['arrival_time']

In [ ]:
le = LabelEncoder()
arrival_time = le.fit_transform(target2)
arrival_time

array([ 834,  181,  900, ..., 4968, 5098, 5124])

In [ ]:
df1['arrival_time_new'] = arrival_time

In [ ]:
target4 = df1['speed']

In [ ]:
le = LabelEncoder()
Speed = le.fit_transform(target4)

In [ ]:
df1['speed_new'] = Speed

In [ ]:
target5 = df1['stop_id_from']

In [ ]:
le = LabelEncoder()
Stop_id_from = le.fit_transform(target5)

In [ ]:
df1['stop_id_from_new'] = Stop_id_from

In [ ]:
target6 = df1['stop_id_to']

In [ ]:
le = LabelEncoder()
Stop_id_to = le.fit_transform(target6)

In [ ]:
df1['stop_id_to_new'] = Stop_id_to

In [ ]:
X=df1

In [ ]:
X=X.drop('trip_id', axis=1)
X=X.drop('arrival_time', axis=1)

In [ ]:
X=X.drop('Number_of_trips', axis=1)
X=X.drop('time', axis=1)
X=X.drop('speed', axis=1)
X=X.drop('stop_id_from', axis=1)
X=X.drop('stop_id_to', axis=1)
X=X.drop('SRI',axis=1)

In [ ]:
y=target

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [ ]:
X = np.column_stack((X['stop_id_from_new'],X['stop_id_to_new'],X['arrival_time_new'],X['speed_new'])) 

In [ ]:
X

array([[ 2875,  3066,   834,  4309],
       [ 2875,  3066,   181,  2975],
       [ 2875,  3066,   900,   695],
       ...,
       [  119,   120,  4968,  3326],
       [ 3837,  3648,  5098, 32222],
       [ 3651,  3650,  5124,  7680]])

In [ ]:
X.shape

(66490, 4)

# STEP SIZE 2

# Many To One - Simple (**20.87%**)

In [ ]:
X = array(X).reshape(33245,2,4)

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(2, 4)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
history = model.fit(X, y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
832/832 [==============================] - 5s 4ms/step - loss: 25647.0430 - accuracy: 0.1584 - val_loss: 5258.8770 - val_accuracy: 0.1891
Epoch 2/1000
832/832 [==============================] - 3s 3ms/step - loss: 1740.8783 - accuracy: 0.1616 - val_loss: 3244.8862 - val_accuracy: 0.1921
Epoch 3/1000
832/832 [==============================] - 3s 3ms/step - loss: 710.4891 - accuracy: 0.1656 - val_loss: 731.2385 - val_accuracy: 0.1997
Epoch 4/1000
832/832 [==============================] - 3s 3ms/step - loss: 384.6029 - accuracy: 0.1701 - val_loss: 885.8189 - val_accuracy: 0.2063
Epoch 5/1000
832/832 [==============================] - 3s 3ms/step - loss: 278.5617 - accuracy: 0.1690 - val_loss: 200.0905 - val_accuracy: 0.2136
Epoch 6/1000
832/832 [==============================] - 3s 3ms/step - loss: 115.6802 - accuracy: 0.1751 - val_loss: 127.2304 - val_accuracy: 0.1856
Epoch 7/1000
832/832 [==============================] - 3s 3ms/step - loss: 77.3190 - accuracy: 0.1753 - va

# Many To One - Stacked (**20.87%**)

In [ ]:
model1 = Sequential()
model1.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(2, 4)))
model1.add(LSTM(100, activation='relu', return_sequences=True))
model1.add(LSTM(50, activation='relu', return_sequences=True))
model1.add(LSTM(25, activation='relu'))
model1.add(Dense(20, activation='relu'))
model1.add(Dense(10, activation='relu'))
model1.add(Dense(1))
model1.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
history1 = model1.fit(X, y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
832/832 [==============================] - 13s 15ms/step - loss: 0.9823 - accuracy: 0.2087 - val_loss: 1.0492 - val_accuracy: 0.2773
Epoch 2/100
832/832 [==============================] - 12s 15ms/step - loss: 0.9825 - accuracy: 0.2087 - val_loss: 1.0448 - val_accuracy: 0.2773
Epoch 3/100
832/832 [==============================] - 13s 15ms/step - loss: 0.9824 - accuracy: 0.2087 - val_loss: 1.0465 - val_accuracy: 0.2773
Epoch 4/100
832/832 [==============================] - 16s 19ms/step - loss: 0.9823 - accuracy: 0.2087 - val_loss: 1.0614 - val_accuracy: 0.2773
Epoch 5/100
832/832 [==============================] - 14s 17ms/step - loss: 0.9822 - accuracy: 0.2087 - val_loss: 1.0393 - val_accuracy: 0.2773
Epoch 6/100
832/832 [==============================] - 13s 15ms/step - loss: 0.9823 - accuracy: 0.2087 - val_loss: 1.0406 - val_accuracy: 0.2773
Epoch 7/100
832/832 [==============================] - 13s 15ms/step - loss: 0.9823 - accuracy: 0.2087 - val_loss: 1.0640 - val_ac

# Many To One - Bidirectional (**20.17%**)

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(2, 4)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
history2 = model.fit(X, y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
832/832 [==============================] - 6s 5ms/step - loss: 95660.6875 - accuracy: 0.1578 - val_loss: 9578.6494 - val_accuracy: 0.1940
Epoch 2/100
832/832 [==============================] - 4s 4ms/step - loss: 2358.2009 - accuracy: 0.1599 - val_loss: 4953.6533 - val_accuracy: 0.2079
Epoch 3/100
832/832 [==============================] - 4s 4ms/step - loss: 1443.2504 - accuracy: 0.1622 - val_loss: 2321.8679 - val_accuracy: 0.2128
Epoch 4/100
832/832 [==============================] - 4s 4ms/step - loss: 688.8494 - accuracy: 0.1711 - val_loss: 1429.7998 - val_accuracy: 0.2385
Epoch 5/100
832/832 [==============================] - 4s 4ms/step - loss: 447.6842 - accuracy: 0.1706 - val_loss: 939.3500 - val_accuracy: 0.1901
Epoch 6/100
832/832 [==============================] - 4s 4ms/step - loss: 250.1703 - accuracy: 0.1707 - val_loss: 691.4286 - val_accuracy: 0.2474
Epoch 7/100
832/832 [==============================] - 4s 5ms/step - loss: 102.1062 - accuracy: 0.1725 - val_l