In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
read=pd.read_csv('FINAL_DATASET.csv')

In [ ]:
read.shape

(66913, 9)

In [ ]:
read['SRI'].replace('', np.nan, inplace=True)

In [ ]:
read.dropna(subset=['SRI'], inplace=True)

In [ ]:
read.shape

(66600, 9)

In [ ]:
read.drop(read.index[read['SRI'] == '#NAME?'], inplace = True)

In [ ]:
read.shape

(66490, 9)

In [ ]:
target = read['Degree_of_congestion']
df1 = read.copy()
df1 = df1.drop('Degree_of_congestion', axis =1)
df1.shape

(66490, 8)

In [ ]:
le = LabelEncoder()
target = le.fit_transform(target)
target

array([3, 2, 0, ..., 0, 3, 2])

In [ ]:
target2 = df1['arrival_time']

In [ ]:
le = LabelEncoder()
arrival_time = le.fit_transform(target2)
arrival_time

array([ 834,  181,  900, ..., 4968, 5098, 5124])

In [ ]:
df1['arrival_time_new'] = arrival_time

In [ ]:
target4 = df1['speed']

In [ ]:
le = LabelEncoder()
Speed = le.fit_transform(target4)

In [ ]:
df1['speed_new'] = Speed

In [ ]:
target5 = df1['stop_id_from']

In [ ]:
le = LabelEncoder()
Stop_id_from = le.fit_transform(target5)

In [ ]:
df1['stop_id_from_new'] = Stop_id_from

In [ ]:
target6 = df1['stop_id_to']

In [ ]:
le = LabelEncoder()
Stop_id_to = le.fit_transform(target6)

In [ ]:
df1['stop_id_to_new'] = Stop_id_to

In [ ]:
X=df1

In [ ]:
X=X.drop('trip_id', axis=1)
X=X.drop('arrival_time', axis=1)

In [ ]:
X=X.drop('Number_of_trips', axis=1)
X=X.drop('time', axis=1)
X=X.drop('speed', axis=1)
X=X.drop('stop_id_from', axis=1)
X=X.drop('stop_id_to', axis=1)
X=X.drop('SRI',axis=1)

In [ ]:
y=target

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [ ]:
X = np.column_stack((X['stop_id_from_new'],X['stop_id_to_new'],X['arrival_time_new'],X['speed_new'])) 

In [ ]:
X

array([[ 2875,  3066,   834,  4309],
       [ 2875,  3066,   181,  2975],
       [ 2875,  3066,   900,   695],
       ...,
       [  119,   120,  4968,  3326],
       [ 3837,  3648,  5098, 32222],
       [ 3651,  3650,  5124,  7680]])

In [ ]:
X.shape

(66490, 4)

# STEP SIZE 5

# Many To One - Simple (**17.82%**)

In [ ]:
X = array(X).reshape(13298,5,4)

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(5, 4)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
trial = model.fit(X, y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
333/333 [==============================] - 4s 6ms/step - loss: 793464.7500 - accuracy: 0.1207 - val_loss: 159953.3438 - val_accuracy: 0.1248
Epoch 2/1000
333/333 [==============================] - 2s 5ms/step - loss: 64165.7461 - accuracy: 0.1242 - val_loss: 86740.6172 - val_accuracy: 0.1237
Epoch 3/1000
333/333 [==============================] - 2s 5ms/step - loss: 34822.5195 - accuracy: 0.1267 - val_loss: 46789.9727 - val_accuracy: 0.1177
Epoch 4/1000
333/333 [==============================] - 2s 5ms/step - loss: 23146.3438 - accuracy: 0.1277 - val_loss: 32832.0039 - val_accuracy: 0.1158
Epoch 5/1000
333/333 [==============================] - 2s 5ms/step - loss: 14911.5186 - accuracy: 0.1217 - val_loss: 25748.8574 - val_accuracy: 0.1188
Epoch 6/1000
333/333 [==============================] - 2s 5ms/step - loss: 11963.9385 - accuracy: 0.1221 - val_loss: 18141.0625 - val_accuracy: 0.1207
Epoch 7/1000
333/333 [==============================] - 2s 5ms/step - loss: 8632.1055 

# Many To One - Stacked (**17.81%**)

In [ ]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(5, 4)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
trial1 = model.fit(X, y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
333/333 [==============================] - 12s 37ms/step - loss: 0.8219 - accuracy: 0.1781 - val_loss: 0.8252 - val_accuracy: 0.1383
Epoch 2/100
333/333 [==============================] - 9s 28ms/step - loss: 0.8224 - accuracy: 0.1781 - val_loss: 0.8263 - val_accuracy: 0.1383
Epoch 3/100
333/333 [==============================] - 9s 28ms/step - loss: 0.8219 - accuracy: 0.1781 - val_loss: 0.8325 - val_accuracy: 0.1383
Epoch 4/100
333/333 [==============================] - 9s 28ms/step - loss: 0.8220 - accuracy: 0.1781 - val_loss: 0.8278 - val_accuracy: 0.1383
Epoch 5/100
333/333 [==============================] - 9s 28ms/step - loss: 0.8222 - accuracy: 0.1781 - val_loss: 0.8235 - val_accuracy: 0.1383
Epoch 6/100
333/333 [==============================] - 9s 27ms/step - loss: 0.8224 - accuracy: 0.1781 - val_loss: 0.8331 - val_accuracy: 0.1383
Epoch 7/100
333/333 [==============================] - 9s 28ms/step - loss: 0.8225 - accuracy: 0.1781 - val_loss: 0.8351 - val_accuracy

# Many To One - Bidirectional (**17.82%**)

In [ ]:
from keras.layers import Bidirectional

model1 = Sequential()
model1.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(5, 4)))
model1.add(Dense(1))
model1.compile(optimizer='adam', loss='mse',metrics=["accuracy"])

In [ ]:
trial2 = model1.fit(X, y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
333/333 [==============================] - 5s 8ms/step - loss: 166652.0938 - accuracy: 0.1172 - val_loss: 59135.9102 - val_accuracy: 0.1090
Epoch 2/100
333/333 [==============================] - 3s 8ms/step - loss: 20473.1895 - accuracy: 0.1230 - val_loss: 19533.7012 - val_accuracy: 0.1147
Epoch 3/100
333/333 [==============================] - 2s 7ms/step - loss: 8725.4609 - accuracy: 0.1228 - val_loss: 11128.6953 - val_accuracy: 0.1169
Epoch 4/100
333/333 [==============================] - 2s 7ms/step - loss: 5288.8257 - accuracy: 0.1224 - val_loss: 4869.6177 - val_accuracy: 0.1173
Epoch 5/100
333/333 [==============================] - 2s 6ms/step - loss: 3157.8442 - accuracy: 0.1274 - val_loss: 4047.7832 - val_accuracy: 0.1117
Epoch 6/100
333/333 [==============================] - 2s 7ms/step - loss: 2125.3386 - accuracy: 0.1242 - val_loss: 2879.2346 - val_accuracy: 0.1071
Epoch 7/100
333/333 [==============================] - 2s 6ms/step - loss: 1421.4182 - accuracy: 0.1